warning: in the working copy of 'PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'PaperNotes/AnomalyDetection/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'PaperNotes/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/fonts/fontawesome/fontawesome-webfont.svg', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-fontsettings/fontsettings.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-fontsettings/website.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-highlight/ebook.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-highlight/website.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-lunr/lunr.min.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-lunr/search-lunr.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-search/lunr.min.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-search/search-engine.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-search/search.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-search/search.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook-plugin-sharing/buttons.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/gitbook.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/style.css', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'gitbook/theme.js', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '数字图像处理/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '数字图像处理/图像增广.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/Normalization/BatchNormalization.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/Normalization/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/基础模型/Transformer.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/基础模型/index.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/训练技巧/K-fold.html', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '深度学习/训练技巧/index.html', LF will be replaced by CRLF the next time Git touches it
[1mdiff --git a/PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.html b/PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.html[m
[1mindex b847027..ade7b8b 100644[m
[1m--- a/PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.html[m
[1m+++ b/PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.html[m
[36m@@ -814,7 +814,7 @@[m [m$$</li>[m
     <script>[m
         var gitbook = gitbook || [];[m
         gitbook.push(function() {[m
[31m-            gitbook.page.hasChanged({"page":{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"next":{"title":"深度学习","level":"1.3","depth":1,"path":"深度学习/README.md","ref":"深度学习/README.md","articles":[{"title":"Normalization","level":"1.3.1","depth":2,"path":"深度学习/Normalization/README.md","ref":"深度学习/Normalization/README.md","articles":[{"title":"BatchNormalization","level":"1.3.1.1","depth":3,"path":"深度学习/Normalization/BatchNormalization.md","ref":"深度学习/Normalization/BatchNormalization.md","articles":[]}]},{"title":"基础模型","level":"1.3.2","depth":2,"path":"深度学习/基础模型/README.md","ref":"深度学习/基础模型/README.md","articles":[{"title":"Transformer","level":"1.3.2.1","depth":3,"path":"深度学习/基础模型/Transformer.md","ref":"深度学习/基础模型/Transformer.md","articles":[]}]},{"title":"训练技巧","level":"1.3.3","depth":2,"path":"深度学习/训练技巧/README.md","ref":"深度学习/训练技巧/README.md","articles":[{"title":"K-fold","level":"1.3.3.1","depth":3,"path":"深度学习/训练技巧/K-fold.md","ref":"深度学习/训练技巧/K-fold.md","articles":[]}]}]},"previous":{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","mtime":"2022-08-03T23:31:39.590Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T13:07:09.755Z"},"basePath":"../..","book":{"language":""}});[m
[32m+[m[32m            gitbook.page.hasChanged({"page":{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"next":{"title":"深度学习","level":"1.3","depth":1,"path":"深度学习/README.md","ref":"深度学习/README.md","articles":[{"title":"Normalization","level":"1.3.1","depth":2,"path":"深度学习/Normalization/README.md","ref":"深度学习/Normalization/README.md","articles":[{"title":"BatchNormalization","level":"1.3.1.1","depth":3,"path":"深度学习/Normalization/BatchNormalization.md","ref":"深度学习/Normalization/BatchNormalization.md","articles":[]}]},{"title":"基础模型","level":"1.3.2","depth":2,"path":"深度学习/基础模型/README.md","ref":"深度学习/基础模型/README.md","articles":[{"title":"Transformer","level":"1.3.2.1","depth":3,"path":"深度学习/基础模型/Transformer.md","ref":"深度学习/基础模型/Transformer.md","articles":[]}]},{"title":"训练技巧","level":"1.3.3","depth":2,"path":"深度学习/训练技巧/README.md","ref":"深度学习/训练技巧/README.md","articles":[{"title":"K-fold","level":"1.3.3.1","depth":3,"path":"深度学习/训练技巧/K-fold.md","ref":"深度学习/训练技巧/K-fold.md","articles":[]}]}]},"previous":{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","mtime":"2022-08-03T23:31:39.590Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T14:27:43.285Z"},"basePath":"../..","book":{"language":""}});[m
         });[m
     </script>[m
 </div>[m
[1mdiff --git a/PaperNotes/AnomalyDetection/index.html b/PaperNotes/AnomalyDetection/index.html[m
[1mindex 681b2b5..28ea59a 100644[m
[1m--- a/PaperNotes/AnomalyDetection/index.html[m
[1m+++ b/PaperNotes/AnomalyDetection/index.html[m
[36m@@ -392,7 +392,7 @@[m
     <script>[m
         var gitbook = gitbook || [];[m
         gitbook.push(function() {[m
[31m-            gitbook.page.hasChanged({"page":{"title":"AnomalyDetection","level":"1.2.1","depth":2,"next":{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]},"previous":{"title":"PaperNotes","level":"1.2","depth":1,"path":"PaperNotes/README.md","ref":"PaperNotes/README.md","articles":[{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"PaperNotes/AnomalyDetection/README.md","mtime":"2022-08-12T13:05:08.353Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T13:07:09.755Z"},"basePath":"../..","book":{"language":""}});[m
[32m+[m[32m            gitbook.page.hasChanged({"page":{"title":"AnomalyDetection","level":"1.2.1","depth":2,"next":{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]},"previous":{"title":"PaperNotes","level":"1.2","depth":1,"path":"PaperNotes/README.md","ref":"PaperNotes/README.md","articles":[{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"PaperNotes/AnomalyDetection/README.md","mtime":"2022-08-12T13:05:08.353Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T14:27:43.285Z"},"basePath":"../..","book":{"language":""}});[m
         });[m
     </script>[m
 </div>[m
[1mdiff --git a/PaperNotes/index.html b/PaperNotes/index.html[m
[1mindex 8cd2d02..ea86690 100644[m
[1m--- a/PaperNotes/index.html[m
[1m+++ b/PaperNotes/index.html[m
[36m@@ -392,7 +392,7 @@[m
     <script>[m
         var gitbook = gitbook || [];[m
         gitbook.push(function() {[m
[31m-            gitbook.page.hasChanged({"page":{"title":"PaperNotes","level":"1.2","depth":1,"next":{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]},"previous":{"title":"Introduction","level":"1.1","depth":1,"path":"README.md","ref":"README.md","articles":[]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"PaperNotes/README.md","mtime":"2022-08-12T13:04:47.686Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T13:07:09.755Z"},"basePath":"..","book":{"language":""}});[m
[32m+[m[32m            gitbook.page.hasChanged({"page":{"title":"PaperNotes","level":"1.2","depth":1,"next":{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]},"previous":{"title":"Introduction","level":"1.1","depth":1,"path":"README.md","ref":"README.md","articles":[]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"PaperNotes/README.md","mtime":"2022-08-12T13:04:47.686Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T14:27:43.285Z"},"basePath":"..","book":{"language":""}});[m
         });[m
     </script>[m
 </div>[m
[1mdiff --git a/index.html b/index.html[m
[1mindex bb687eb..2f6681a 100644[m
[1m--- a/index.html[m
[1m+++ b/index.html[m
[36m@@ -387,7 +387,7 @@[m
     <script>[m
         var gitbook = gitbook || [];[m
         gitbook.push(function() {[m
[31m-            gitbook.page.hasChanged({"page":{"title":"Introduction","level":"1.1","depth":1,"next":{"title":"PaperNotes","level":"1.2","depth":1,"path":"PaperNotes/README.md","ref":"PaperNotes/README.md","articles":[{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"README.md","mtime":"2022-08-12T13:04:27.160Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T13:07:09.755Z"},"basePath":".","book":{"language":""}});[m
[32m+[m[32m            gitbook.page.hasChanged({"page":{"title":"Introduction","level":"1.1","depth":1,"next":{"title":"PaperNotes","level":"1.2","depth":1,"path":"PaperNotes/README.md","ref":"PaperNotes/README.md","articles":[{"title":"AnomalyDetection","level":"1.2.1","depth":2,"path":"PaperNotes/AnomalyDetection/README.md","ref":"PaperNotes/AnomalyDetection/README.md","articles":[{"title":"SkeletonAnomalyDetection2019","level":"1.2.1.1","depth":3,"path":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","ref":"PaperNotes/AnomalyDetection/SkeletonAnomalyDetection2019.md","articles":[]}]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"README.md","mtime":"2022-08-12T13:04:27.160Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T14:27:43.285Z"},"basePath":".","book":{"language":""}});[m
         });[m
     </script>[m
 </div>[m
[1mdiff --git "a/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/index.html" "b/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/index.html"[m
[1mindex 464d1ac..4decf3f 100644[m
[1m--- "a/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/index.html"[m
[1m+++ "b/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/index.html"[m
[36m@@ -389,7 +389,7 @@[m
     <script>[m
         var gitbook = gitbook || [];[m
         gitbook.push(function() {[m
[31m-            gitbook.page.hasChanged({"page":{"title":"数字图像处理","level":"1.4","depth":1,"next":{"title":"图像增广","level":"1.4.1","depth":2,"path":"数字图像处理/图像增广.md","ref":"数字图像处理/图像增广.md","articles":[]},"previous":{"title":"K-fold","level":"1.3.3.1","depth":3,"path":"深度学习/训练技巧/K-fold.md","ref":"深度学习/训练技巧/K-fold.md","articles":[]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"数字图像处理/README.md","mtime":"2022-08-12T12:29:57.724Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T13:07:09.755Z"},"basePath":"..","book":{"language":""}});[m
[32m+[m[32m            gitbook.page.hasChanged({"page":{"title":"数字图像处理","level":"1.4","depth":1,"next":{"title":"图像增广","level":"1.4.1","depth":2,"path":"数字图像处理/图像增广.md","ref":"数字图像处理/图像增广.md","articles":[]},"previous":{"title":"K-fold","level":"1.3.3.1","depth":3,"path":"深度学习/训练技巧/K-fold.md","ref":"深度学习/训练技巧/K-fold.md","articles":[]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":false,"vk":false,"all":["facebook","google","twitter","weibo","instapaper"]},"fontsettings":{"theme":"white","family":"sans","size":2},"theme-default":{"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"},"showLevel":false}},"structure":{"langs":"LANGS.md","readme":"README.md","glossary":"GLOSSARY.md","summary":"SUMMARY.md"},"pdf":{"pageNumbers":true,"fontSize":12,"fontFamily":"Arial","paperSize":"a4","chapterMark":"pagebreak","pageBreaksBefore":"/","margin":{"right":62,"left":62,"top":56,"bottom":56}},"styles":{"website":"styles/website.css","pdf":"styles/pdf.css","epub":"styles/epub.css","mobi":"styles/mobi.css","ebook":"styles/ebook.css","print":"styles/print.css"}},"file":{"path":"数字图像处理/README.md","mtime":"2022-08-12T12:29:57.724Z","type":"markdown"},"gitbook":{"version":"3.2.3","time":"2022-08-12T14:27:43.285Z"},"basePath":"..","book":{"language":""}});[m
         });[m
     </script>[m
 </div>[m
[1mdiff --git "a/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/\345\233\276\345\203\217\345\242\236\345\271\277.html" "b/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/\345\233\276\345\203\217\345\242\236\345\271\277.html"[m
[1mindex 77dcc3a..03f5f71 100644[m
[1m--- "a/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/\345\233\276\345\203\217\345\242\236\345\271\277.html"[m
[1m+++ "b/\346\225\260\345\255\227\345\233\276\345\203\217\345\244\204\347\220\206/\345\233\276\345\203\217\345\242\236\345\271\277.html"[m
[36m@@ -423,7 +423,7 @@[m
     <script>[m
         var gitbook = gitbook || [];[m
         gitbook.push(function() {[m
[31m-            gitbook.page.hasChanged({"page":{"title":"图像增广","level":"1.4.1","depth":2,"previous":{"title":"数字图像处理","level":"1.4","depth":1,"path":"数字图像处理/README.md","ref":"数字图像处理/README.md","articles":[{"title":"图像增广","level":"1.4.1","depth":2,"path":"数字图像处理/图像增广.md","ref":"数字图像处理/图像增广.md","articles":[]}]},"dir":"ltr"},"config":{"gitbook":"*","theme":"default","variables":{},"plugins":[],"pluginsConfig":{"highlight":{},"search":{},"lunr":{"maxIndexSize":1000000,"ignoreSpecialCharacters":false},"sharing":{"facebook":true,"twitter":true,"google":false,"weibo":false,"instapaper":fals